export const SERVICES = [
  {
    slug: 'seo-local-seo',
    title: 'SEO and Local SEO',
    shortTitle: 'SEO',
    heading: 'SEO Specialist',
    description: 'Search engine optimisation built for UK businesses that need to rank in their town and region.',
    icon: '🔍',
    expertiseSlug: 'seo',
  },
  {
    slug: 'ai-search-optimisation',
    title: 'AI Search Optimisation (AEO/GEO)',
    shortTitle: 'AI Search',
    heading: 'AI Search Optimisation',
    description: 'Optimisation for ChatGPT, Gemini, Perplexity, and Google AI Overviews.',
    icon: '🤖',
    expertiseSlug: 'ai-search-optimisation',
  },
  {
    slug: 'google-business-profile',
    title: 'Google Business Profile Management',
    shortTitle: 'Google Business Profile',
    heading: 'Google Business Profile',
    description: 'Google Business Profile management that produces calls, not just views.',
    icon: '📍',
    expertiseSlug: 'seo',
  },
  {
    slug: 'ai-receptionist-lead-response',
    title: 'AI Receptionist and Lead Response',
    shortTitle: 'AI Receptionist',
    heading: 'AI Receptionist',
    description: 'AI that answers every enquiry in minutes, 24/7, and follows up automatically.',
    icon: '💬',
    expertiseSlug: 'ai-agents',
  },
  {
    slug: 'google-ads-api',
    title: 'Google Ads via the Ads API',
    shortTitle: 'Google Ads',
    heading: 'Google Ads Engineering',
    description: 'Google Ads managed through code and the Ads API, not an agency clicking buttons.',
    icon: '📊',
    expertiseSlug: 'google-ads-api',
  },
  {
    slug: 'website-development',
    title: 'Custom Website and Web App Development',
    shortTitle: 'Web Development',
    heading: 'Website Development',
    description: 'Performance-first websites built to rank and convert, engineered not themed.',
    icon: '💻',
    expertiseSlug: 'programmatic-seo',
  },
  {
    slug: 'crm-email-marketing',
    title: 'CRM and Email Marketing Automation',
    shortTitle: 'CRM and Email',
    heading: 'CRM and Email Automation',
    description: 'CRM systems that capture and follow up every lead, and email campaigns that turn old enquiries into booked work.',
    icon: '📧',
    expertiseSlug: 'ai-agents',
  }  {
    slug: 'ai-implementation',
    title: 'AI Implementation',
    shortTitle: 'AI Implementation',
    heading: 'AI Implementation',
    description: 'End-to-end AI implementation for UK businesses: audit, build, handover, and ongoing support.',
    icon: '⚙️',
    expertiseSlug: 'ai-implementation',
  },
  {
    slug: 'digital-marketing',
    title: 'Digital Marketing',
    shortTitle: 'Digital Marketing',
    heading: 'Digital Marketing',
    description: 'Multi-channel digital marketing: search, paid, email, content, and automation -- all AI-enhanced.',
    icon: '📈',
    expertiseSlug: 'digital-marketing',
  },
  {
    slug: 'web-design',
    title: 'Web Design and Development',
    shortTitle: 'Web Design',
    heading: 'Web Design and Development',
    description: 'Performance-first websites engineered to rank and convert, built with Next.js and static generation.',
    icon: '🖥️',
    expertiseSlug: 'web-design-development',
  },
  {
    slug: 'marketing-automation',
    title: 'CRM and Marketing Automation',
    shortTitle: 'Marketing Automation',
    heading: 'Marketing Automation',
    description: 'Automated lead capture, immediate response, follow-up sequences, and reporting without manual intervention.',
    icon: '🔄',
    expertiseSlug: 'marketing-automation',
  },
  {
    slug: 'ai-content-systems',
    title: 'AI Content Systems',
    shortTitle: 'AI Content',
    heading: 'AI Content Systems',
    description: 'AI-assisted content strategy and production at scale, structured for search and AI search visibility.',
    icon: '✍️',
    expertiseSlug: 'ai-content-systems',
  },
  {
    slug: 'google-ranking',
    title: 'Rank Number One on Google',
    shortTitle: 'Google Ranking',
    heading: 'Rank Number One on Google',
    description: 'First-position Google rankings for commercial keywords, with a ranked-or-refunded guarantee.',
    icon: '🥇',
    expertiseSlug: 'google-ranking',
  },
];

export const TIER_1_LOCATIONS = [
  {
    slug: 'stoke-on-trent',
    name: 'Stoke-on-Trent',
    region: 'Staffordshire',
    county: 'Staffordshire',
    tier: 1,
    intro: 'Stoke-on-Trent is the base. Every campaign, build, and system runs from here. That means local knowledge is real, response times are fast, and I can meet in person.',
    localNote: 'The Potteries economy runs on trades, manufacturing, retail, and services — all industries where appearing first on Google and in AI search converts directly to enquiries.',
  },
  {
    slug: 'stafford',
    name: 'Stafford',
    region: 'Staffordshire',
    county: 'Staffordshire',
    tier: 1,
    intro: 'Stafford businesses compete for the same local searches as Stoke firms but often with less SEO investment from competitors. That gap is the opportunity.',
    localNote: 'County town with a strong professional services and retail sector. Local search intent is high and the competitive bar is lower than the nearest cities.',
  },
  {
    slug: 'newcastle-under-lyme',
    name: 'Newcastle-under-Lyme',
    region: 'Staffordshire',
    county: 'Staffordshire',
    tier: 1,
    intro: 'Newcastle-under-Lyme sits adjacent to Stoke-on-Trent and shares much of its local search geography. Businesses here often compete for the same searches as Stoke firms.',
    localNote: 'Large student population from Keele University creates demand for local services. Trade businesses, hospitality, and retail all benefit from local SEO investment here.',
  },
  {
    slug: 'crewe',
    name: 'Crewe',
    region: 'Cheshire',
    county: 'Cheshire East',
    tier: 1,
    intro: 'Crewe is a strong logistics and engineering hub. Businesses here benefit from national connectivity but compete hard in local searches for services and trades.',
    localNote: 'Rail hub and engineering town with growing business services sector. Local search competition is moderate, making well-executed SEO campaigns effective quickly.',
  },
  {
    slug: 'birmingham',
    name: 'Birmingham',
    region: 'West Midlands',
    county: 'West Midlands',
    tier: 1,
    intro: 'Birmingham is the UK\'s second city and a major SEO battleground. Ranking here takes more work but the commercial upside is proportionally larger.',
    localNote: 'Diverse economy spanning professional services, hospitality, construction, and retail. AI search visibility is increasingly important as Birmingham searches are heavy in Google AI Overviews.',
  },
  {
    slug: 'manchester',
    name: 'Manchester',
    region: 'Greater Manchester',
    county: 'Greater Manchester',
    tier: 1,
    intro: 'Manchester is one of the most competitive SEO markets in the UK outside London. Appearing in AI search answers here can leapfrog businesses ahead of well-funded agency clients.',
    localNote: 'Technology, creative, and professional services dominate. Manchester businesses searching for B2B services now increasingly get answers from ChatGPT and Perplexity rather than Google alone.',
  },
];

export const TIER_2_LOCATIONS = [
  { slug: 'london', name: 'London', region: 'London', county: 'Greater London', tier: 2 },
  { slug: 'leeds', name: 'Leeds', region: 'West Yorkshire', county: 'West Yorkshire', tier: 2 },
  { slug: 'liverpool', name: 'Liverpool', region: 'Merseyside', county: 'Merseyside', tier: 2 },
  { slug: 'sheffield', name: 'Sheffield', region: 'South Yorkshire', county: 'South Yorkshire', tier: 2 },
  { slug: 'nottingham', name: 'Nottingham', region: 'Nottinghamshire', county: 'Nottinghamshire', tier: 2 },
  { slug: 'bristol', name: 'Bristol', region: 'Bristol', county: 'Bristol', tier: 2 },
];

export const TIER_3_LOCATIONS = [
  { slug: 'lichfield', name: 'Lichfield', region: 'Staffordshire', county: 'Staffordshire', tier: 3 },
  { slug: 'tamworth', name: 'Tamworth', region: 'Staffordshire', county: 'Staffordshire', tier: 3 },
  { slug: 'burton-on-trent', name: 'Burton-on-Trent', region: 'Staffordshire', county: 'Staffordshire', tier: 3 },
  { slug: 'cannock', name: 'Cannock', region: 'Staffordshire', county: 'Staffordshire', tier: 3 },
  { slug: 'rugeley', name: 'Rugeley', region: 'Staffordshire', county: 'Staffordshire', tier: 3 },
  { slug: 'stone', name: 'Stone', region: 'Staffordshire', county: 'Staffordshire', tier: 3 },
  { slug: 'leek', name: 'Leek', region: 'Staffordshire', county: 'Staffordshire', tier: 3 },
  { slug: 'congleton', name: 'Congleton', region: 'Cheshire', county: 'Cheshire East', tier: 3 },
  { slug: 'macclesfield', name: 'Macclesfield', region: 'Cheshire', county: 'Cheshire East', tier: 3 },
  { slug: 'nantwich', name: 'Nantwich', region: 'Cheshire', county: 'Cheshire East', tier: 3 },
  { slug: 'chester', name: 'Chester', region: 'Cheshire', county: 'Cheshire West and Chester', tier: 3 },
];

export const ALL_LOCATIONS = [...TIER_1_LOCATIONS, ...TIER_2_LOCATIONS, ...TIER_3_LOCATIONS];
